version: 2

sources:
  - name: raw
    description: Raw layer - unprocessed data from source systems
    database: ecommerce_dw
    schema: raw
    tables:
      - name: raw_products
        description: Products from DummyJSON API
      
      - name: raw_customers
        description: Generated customer data
      
      - name: raw_orders
        description: Generated order data

      - name: raw_order_items
        description: Order line items

      - name: raw_transactions
        description: Payment transactions

models:
  - name: stg_products
    description: Cleaned and typed product data from raw layer
    columns:
      - name: source_product_id
        description: Unique product identifier
        tests:
          - not_null
          - unique
      - name: product_name
        description: Product name
        tests:
          - not_null
      - name: price
        description: Product price (decimal)
        tests:
          - not_null
  
  - name: stg_customers
    description: Cleaned and typed customer data from raw layer
    columns:
      - name: source_customer_id
        description: Unique customer identifier from source
        tests:
          - not_null
          - unique
      - name: email
        description: Customer email address
        tests:
          - not_null
      - name: full_name
        description: Customer full name (concatenated)
  
  - name: stg_transactions
    description: Cleaned and typed transaction data from raw layer
    columns:
      - name: source_transaction_id
        description: Unique transaction identifier
        tests:
          - not_null
          - unique
      - name: source_order_id
        description: Order identifier
        tests:
          - not_null
      - name: transaction_date
        description: Transaction date
        tests:
          - not_null
      - name: transaction_amount
        description: Transaction amount
        tests:
          - not_null

  - name: stg_orders
    description: Cleaned and typed order data from raw layer
    columns:
      - name: source_order_id
        description: Unique order identifier
        tests:
          - not_null
          - unique
      - name: source_customer_id
        description: Customer identifier
        tests:
          - not_null
      - name: order_date
        description: Order date
        tests:
          - not_null
      - name: total_amount
        description: Total order amount
        tests:
          - not_null
  
  - name: stg_order_items
    description: Cleaned and typed order item data from raw layer
    columns:
      - name: source_order_item_id
        description: Unique order item identifier
        tests:
          - not_null
          - unique
      - name: source_order_id
        description: Order identifier
        tests:
          - not_null
      - name: source_product_id
        description: Product identifier
        tests:
          - not_null
      - name: quantity
        description: Quantity
        tests:
          - not_null
      - name: unit_price
        description: Unit price (decimal)
        tests:
          - not_null
      - name: total_price
        description: Total line item price (decimal)
        tests:
          - not_null

