CREATE OR REPLACE TABLE raw.raw_order_items (
    ID INT IDENTITY PRIMARY KEY,
    SOURCE_ORDER_ITEM_ID INT,
    SOURCE_ORDER_ID INT,
    SOURCE_PRODUCT_ID INT,
    QUANTITY INT,
    UNIT_PRICE FLOAT,
    TOTAL_PRICE FLOAT,
    GENERATED_AT TIMESTAMP_TZ,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID TIMESTAMP_TZ,
    SOURCE STRING
);
