CREATE OR REPLACE TABLE raw.raw_orders (
    ID INT IDENTITY PRIMARY KEY,
    SOURCE_ORDER_ID INT,
    SOURCE_CUSTOMER_ID INT,
    ORDER_DATE TIMESTAMP_TZ,
    ORDER_STATUS STRING,
    TOTAL_AMOUNT FLOAT,
    PAYMENT_METHOD STRING,
    SHIPPING_ADDRESS STRING,
    GENERATED_AT TIMESTAMP_TZ,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID TIMESTAMP_TZ,
    SOURCE STRING
);

