CREATE OR REPLACE TABLE raw.raw_transactions (
    id INT IDENTITY PRIMARY KEY,
    SOURCE_TRANSACTION_ID INT,
    SOURCE_ORDER_ID INT,
    TRANSACTION_TYPE STRING,
    AMOUNT FLOAT,
    PAYMENT_METHOD STRING,
    TRANSACTION_STATUS STRING,
    TRANSACTION_DATE TIMESTAMP_TZ,
    PROCESSOR_TRANSACTION_ID STRING,
    PROCESSOR_NAME STRING,
    CARD_LAST_FOUR STRING,
    GENERATED_AT TIMESTAMP_TZ,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID TIMESTAMP_TZ,
    SOURCE STRING
);


