CREATE OR REPLACE TABLE raw.raw_products 
(
id INT IDENTITY PRIMARY KEY,
source_product_id INT,
product_name STRING,
brand STRING,
category STRING,
price FLOAT,
discount_percentage FLOAT,
rating FLOAT,
stock INT,
description STRING,
thumbnail STRING,
weight FLOAT,
width FLOAT,
height FLOAT,
depth FLOAT,
warranty_info STRING,
shipping_info STRING,
availability_status STRING,
return_policy STRING,
minimum_order_qty INT,
barcode STRING,
qr_code STRING,
generated_at TIMESTAMP_TZ,
loaded_at TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
batch_id TIMESTAMP_TZ,
SOURCE STRING
)